##### Numpy ------> Numeric Python. It also called as Vector
##### [
 ##### [1,2,3],
 ##### [4,5,6],
 ##### [1,2,3]
##### ]  multidimensional Arrays
##### ipynb ---> I python notebook

In [2]:
import numpy as np

##### Creating array from list

In [3]:
arr_1D = np.array([1,2,3,4,5])
print("1-D Array : ",arr_1D)

arr_2D = np.array([[1,2,3,4],[1,2,3,4]])
print("2-D Array : ",arr_2D)

1-D Array :  [1 2 3 4 5]
2-D Array :  [[1 2 3 4]
 [1 2 3 4]]


##### List Vs numpy array

In [4]:
py_list = [1,2,3]
print("Python List multiplication : ", py_list *2 ) 
np_array =np.array([1,2,3])
print("Python List multiplication : ", np_array *2 ) # Element wise multiplication

import time 
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n List operation time : ", time.time() - start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy operation time : ", time.time() - start)

Python List multiplication :  [1, 2, 3, 1, 2, 3]
Python List multiplication :  [2 4 6]

 List operation time :  0.014889001846313477

 Numpy operation time :  0.019193172454833984


##### Creating Array from scratch

In [5]:
zeros = np.zeros((3,4))
print("Zeros Array : \n", zeros)
ones = np.ones((2,3))
print("Ones Array : \n",ones)
full = np.full((2,3), 7)
print("Full Array : \n",full)

Zeros Array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array : 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array : 
 [[7 7 7]
 [7 7 7]]


In [6]:
random = np.random.random((2,3))
print("Random Array : \n",random) 

sequence = np.arange(0,10,2)
print("Sequence Array : \n",sequence) 

Random Array : 
 [[0.84068832 0.07436726 0.10140695]
 [0.95256966 0.54519537 0.34887242]]
Sequence Array : 
 [0 2 4 6 8]


##### Vector , Matrix , and Tensor

In [7]:
vector = np.array([1,2,3])
print("Vector : ", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix : ", matrix)

tensor = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[8,9,10]]])
print("Tensor : ", tensor)


Vector :  [1 2 3]
Matrix :  [[1 2 3]
 [4 5 6]]
Tensor :  [[[ 1  2  3]
  [ 3  4  5]]

 [[ 5  6  7]
  [ 8  9 10]]]


##### Array Properties

In [8]:
arr = np.array([[1,2,3], [4,5,6]])
print("Shape : ", arr.shape)
print("Dimension : ", arr.ndim)
print("Size : ", arr.size)
print("DType : ", arr.dtype)

Shape :  (2, 3)
Dimension :  2
Size :  6
DType :  int64


##### Array Reshaping

In [9]:
arr = np.arange(12)
print("Original Array : ", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped Array : ", reshaped)

flattened = reshaped.flatten()
print("Flattended Array :", flattened)

# ravel returns view , instead of copy
raveled = reshaped.ravel()
print("\n Raveled Array : ", raveled)

# Transpose
transpose = reshaped.T
print("Transposed Array : \n", transpose)


Original Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattended Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


#### Numpy Array Operations


In [10]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative  Indexing ",arr[-3:])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative  Indexing  [ 8  9 10]


In [11]:
arr_2D = np.array([[1,2,3,4],[5,6,7,8]])
print("Specefic Element: ", arr_2D[1,2])
print("Entire Row :", arr_2D[1])
print("Entire row :",arr_2D[:,1] )

Specefic Element:  7
Entire Row : [5 6 7 8]
Entire row : [2 6]


#### Sorting

In [12]:
unsorted = np.array([3,1,4,2,5])
print("Sorted Array : ", np.sort(unsorted))

arr_2D_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2-D Array by column :", np.sort(arr_2D_unsorted, axis=0))

Sorted Array :  [1 2 3 4 5]
Sorted 2-D Array by column : [[1 1]
 [2 2]
 [3 3]]


#### Array Filter

In [13]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
even_no = num[num % 2 == 0]
odd_no = num[num % 2 != 0]
print("Even Numbers : " ,even_no)
print("Odd Numbers : ", odd_no)

Even Numbers :  [ 2  4  6  8 10]
Odd Numbers :  [1 3 5 7 9]


#### Filter with Mask

In [14]:
mask = num  > 5 
print("Number greater than 5 : ", num[mask]) 

Number greater than 5 :  [ 6  7  8  9 10]


#### Fancy indexing vs np.where()

In [15]:
indices = [0, 2, 4]
print(num[indices])
where_result = np.where(num>5)
print(where_result)
print("NP where ", num[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]


#### Condition Array

In [19]:
condition_array = np.where(num > 5, num*4, num)
print("Condition Array : ", condition_array)

Condition Array :  [ 1  2  3  4  5 24 28 32 36 40]


#### Adding and Removing Data

In [21]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1, arr2))
print("Combined Array : ", combined)

Combined Array :  [1 2 3 4 5 6]


#### Array Compatibility

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibilty Shapes : ", a.shape == b.shape == c.shape)

Compatibilty Shapes :  True
