##### Numpy ------> Numeric Python. It also called as Vector
##### [
 ##### [1,2,3],
 ##### [4,5,6],
 ##### [1,2,3]
##### ]  multidimensional Arrays
##### ipynb ---> I python notebook

In [ ]:
import numpy as np

##### Creating array from list

In [4]:
arr_1D = np.array([1,2,3,4,5])
print("1-D Array : ",arr_1D)

arr_2D = np.array([[1,2,3,4],[1,2,3,4]])
print("2-D Array : ",arr_2D)

1-D Array :  [1 2 3 4 5]
2-D Array :  [[1 2 3 4]
 [1 2 3 4]]


##### List Vs numpy array

In [9]:
py_list = [1,2,3]
print("Python List multiplication : ", py_list *2 ) 
np_array =np.array([1,2,3])
print("Python List multiplication : ", np_array *2 ) # Element wise multiplication

import time 
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n List operation time : ", time.time() - start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy operation time : ", time.time() - start)

Python List multiplication :  [1, 2, 3, 1, 2, 3]
Python List multiplication :  [2 4 6]

 List operation time :  0.010409355163574219

 Numpy operation time :  0.010942935943603516


##### Creating Array from scratch

In [ ]:
zeros = np.zeros((3,4))
print("Zeros Array : \n", zeros)
ones = np.ones((2,3))
print("Ones Array : \n",ones)
full = np.full((2,3), 7)
print("Full Array : \n",full)

Zeros Array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array : 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array : 
 [[7 7 7]
 [7 7 7]]


In [15]:
random = np.random.random((2,3))
print("Random Array : \n",random) 

sequence = np.arange(0,10,2)
print("Sequence Array : \n",sequence) 

Random Array : 
 [[0.42928077 0.40132449 0.0308134 ]
 [0.56393213 0.79464331 0.25120738]]
Sequence Array : 
 [0 2 4 6 8]


##### Vector , Matrix , and Tensor

In [18]:
vector = np.array([1,2,3])
print("Vector : ", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix : ", matrix)

tensor = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[8,9,10]]])
print("Tensor : ", tensor)


Vector :  [1 2 3]
Matrix :  [[1 2 3]
 [4 5 6]]
Tensor :  [[[ 1  2  3]
  [ 3  4  5]]

 [[ 5  6  7]
  [ 8  9 10]]]


##### Array Properties

In [19]:
arr = np.array([[1,2,3], [4,5,6]])
print("Shape : ", arr.shape)
print("Dimension : ", arr.ndim)
print("Size : ", arr.size)
print("DType : ", arr.dtype)

Shape :  (2, 3)
Dimension :  2
Size :  6
DType :  int64


##### Array Reshaping

In [24]:
arr = np.arange(12)
print("Original Array : ", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped Array : ", reshaped)

flattened = reshaped.flatten()
print("Flattended Array :", flattened)

# ravel returns view , instead of copy
raveled = reshaped.ravel()
print("\n Raveled Array : ", raveled)

# Transpose
transpose = reshaped.T
print("Transposed Array : \n", transpose)


Original Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattended Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
